name: Deploy to Github Pages

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: .
                  clean: true
                  single-commit: true
